#ifndef WIRING_CONSTS_H
#define WIRING_CONSTS_H

// motor constants
#define LEFT_MOTOR_PIN_A 7
#define LEFT_MOTOR_PIN_B 8
#define LEFT_MOTOR_PIN_PWM 9

#define RIGHT_MOTOR_PIN_A 0
#define RIGHT_MOTOR_PIN_B 0
#define RIGHT_MOTOR_PIN_PWM 0

// encoder constants
#define LEFT_MOTOR_ENCODER_PIN_INTERCEPT 2
#define LEFT_MOTOR_ENCODER_PIN_NORMAL 3

#define RIGHT_MOTOR_ENCODER_PIN_INTERCEPT 0
#define RIGHT_MOTOR_ENCODER_PIN_NORMAL 0


// distance sensors
#define FORWARD_DISTANCE_SENSOR_ADDRESS 0x20
#define FORWARD_DISTANCE_SENSOR_PIN 11

#define LEFT_DISTANCE_SENSOR_ADDRESS 0x22
#define LEFT_DISTANCE_SENSOR_PIN 10

#define RIGHT_DISTANCE_SENSOR_ADDRESS 0x24
#define RIGHT_DISTANCE_SENSOR_PIN 13

#endif
